---
cisco3:
    hostname: cisco3.lasthop.io
    groups:
      - ios

cisco4:
    hostname: cisco4.lasthop.io
    groups:
      - ios

nxos1:
    hostname: nxos1.lasthop.io
    groups:
      - nxos
    data:
      interfaces:
        - id: Eth1/1
          description: TO-NXOS2
          ip: 172.31.254.1
          mask: 255.255.255.0
        - id: lo101
          description: Router-ID and network 1 statement
          ip: 172.31.101.101
          mask: 255.255.255.255
      router_id: 172.31.101.101
      bgp:
        local_as: 22
        networks:
          - id: 172.31.101.101/32
        prefix_lists:
          - seq: 5
            network: 172.31.101.101/32
            action: permit
            name: TO-172.31.254.2
        route_maps:
          - seq: 5
            action: permit
            name: TO-NXOS2
            prefix_list: TO-172.31.254.2
        peers:
          - ip: 172.31.254.2
            remote_as: 22
            net_out: 172.31.101.101/32
            route_map_out: TO-NXOS2

nxos2:
    hostname: nxos2.lasthop.io
    groups:
      - nxos
    data:
      interfaces:
        - id: Eth1/1
          description: TO-NXOS1
          ip: 172.31.254.2
          mask: 255.255.255.0
        - id: lo102
          description: Router-ID and network 2 statement
          ip: 172.31.101.102
          mask: 255.255.255.255
      router_id: 172.31.101.102
      bgp:
        local_as: 22
        networks:
          - id: 172.31.101.102/32
        peers:
          - ip: 172.31.254.1
            remote_as: 22
            net_out: 172.31.101.102/32
            route_map_out: RM_BGP_NXOS1_Peer

arista1:
    hostname: arista1.lasthop.io
    groups:
      - eos

arista2:
    hostname: arista2.lasthop.io
    groups:
      - eos

arista3:
    hostname: arista3.lasthop.io
    groups:
      - eos

arista4:
    hostname: arista4.lasthop.io
    groups:
      - eos

srx2:
    hostname: srx2.lasthop.io
    groups:
      - junos
