---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "~/nornir_inventory/hosts.yaml"
    group_file: "groups.yaml"
    defaults_file: "~/nornir_inventory/defaults.yaml"
logging:
  enabled: True
  level: DEBUG
  log_file: log.txt
  to_console: False
runner:
  plugin: serial