---
cisco3:
    hostname: cisco3.lasthop.io
    groups:
      - ios

cisco4:
    hostname: cisco4.lasthop.io
    groups:
      - ios

nxos1:
    hostname: nxos1.lasthop.io
    groups:
      - nxos
    data:
      bgp_asn: 22
      bgp_remote_as_asn: 22
      bgp_router_id: 172.24.16.1
      bgp_peer: 172.24.32.12
      bgp_remote_asn: 22
      int_name: Ethernet1/2
      ip_address: 172.24.32.11
      ip_mask: 255.255.255.0

nxos2:
    hostname: nxos2.lasthop.io
    groups:
      - nxos
    data:
      bgp_asn: 22
      bgp_remote_as_asn: 22
      bgp_router_id: 172.24.16.2
      bgp_peer: 172.24.32.11
      bgp_remote_asn: 22
      int_name: Ethernet1/2
      ip_address: 172.24.32.12
      ip_mask: 255.255.255.0

arista1:
    hostname: arista1.lasthop.io
    groups:
      - eos

arista2:
    hostname: arista2.lasthop.io
    groups:
      - eos

arista3:
    hostname: arista3.lasthop.io
    groups:
      - eos

arista4:
    hostname: arista4.lasthop.io
    groups:
      - eos

srx2:
    hostname: srx2.lasthop.io
    groups:
      - junos
